import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import UserRec from '../components/UserRec'

const Users: NextPage = () => {

  const namez = useFormInput('');
  const surnamez = useFormInput('');


  function useFormInput(defVal: string) {
    const [value, setValue] = useState(defVal);
    function handleChange(e: any) {
      setValue(e.target.value);
    }
    return {
      value,
      onChange: handleChange
    };
  }

  function userAdd() {
    console.log('userAdd: name=' + namez + ', surname=' + surnamez);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <p className={styles.description}>{`Ім'я`} <br /><input {...namez} /></p>
          </div>
          <div className={styles.card}>
            <p className={styles.description}> {`Прізвище`}<br /> <input {...surnamez} /></p>
          </div>
          <div className={styles.card}>

            <p className={styles.description}><button onClick={userAdd}>Зберегти</button> </p>
          </div>
        </div>


        <div className={styles.main2} >
          <UserRec text=' text ' href='testhref'></UserRec>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/490-crocodile.svg" alt="Crocodile Logo" width={72} height={72} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export default Users
